version: "3.7"

services:
  oathkeeper:
    image: oryd/oathkeeper:v0.40.6
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./.oathkeeper:/etc/config/oathkeeper

networks:
  intranet:
